/**
 */
package dev.abunai.confidentiality.analysis.model.uncertainty.provider;

import dev.abunai.confidentiality.analysis.model.uncertainty.util.UncertaintyAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class UncertaintyItemProviderAdapterFactory extends UncertaintyAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UncertaintyItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link dev.abunai.confidentiality.analysis.model.uncertainty.UncertaintySourceCollection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UncertaintySourceCollectionItemProvider uncertaintySourceCollectionItemProvider;

	/**
	 * This creates an adapter for a {@link dev.abunai.confidentiality.analysis.model.uncertainty.UncertaintySourceCollection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUncertaintySourceCollectionAdapter() {
		if (uncertaintySourceCollectionItemProvider == null) {
			uncertaintySourceCollectionItemProvider = new UncertaintySourceCollectionItemProvider(this);
		}

		return uncertaintySourceCollectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dev.abunai.confidentiality.analysis.model.uncertainty.BehaviorUncertaintySource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BehaviorUncertaintySourceItemProvider behaviorUncertaintySourceItemProvider;

	/**
	 * This creates an adapter for a {@link dev.abunai.confidentiality.analysis.model.uncertainty.BehaviorUncertaintySource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBehaviorUncertaintySourceAdapter() {
		if (behaviorUncertaintySourceItemProvider == null) {
			behaviorUncertaintySourceItemProvider = new BehaviorUncertaintySourceItemProvider(this);
		}

		return behaviorUncertaintySourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dev.abunai.confidentiality.analysis.model.uncertainty.BehaviorUncertaintyScenario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BehaviorUncertaintyScenarioItemProvider behaviorUncertaintyScenarioItemProvider;

	/**
	 * This creates an adapter for a {@link dev.abunai.confidentiality.analysis.model.uncertainty.BehaviorUncertaintyScenario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBehaviorUncertaintyScenarioAdapter() {
		if (behaviorUncertaintyScenarioItemProvider == null) {
			behaviorUncertaintyScenarioItemProvider = new BehaviorUncertaintyScenarioItemProvider(this);
		}

		return behaviorUncertaintyScenarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dev.abunai.confidentiality.analysis.model.uncertainty.ExternalUncertaintySourceInResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExternalUncertaintySourceInResourceItemProvider externalUncertaintySourceInResourceItemProvider;

	/**
	 * This creates an adapter for a {@link dev.abunai.confidentiality.analysis.model.uncertainty.ExternalUncertaintySourceInResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExternalUncertaintySourceInResourceAdapter() {
		if (externalUncertaintySourceInResourceItemProvider == null) {
			externalUncertaintySourceInResourceItemProvider = new ExternalUncertaintySourceInResourceItemProvider(this);
		}

		return externalUncertaintySourceInResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dev.abunai.confidentiality.analysis.model.uncertainty.ExternalUncertaintySourceInUsage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExternalUncertaintySourceInUsageItemProvider externalUncertaintySourceInUsageItemProvider;

	/**
	 * This creates an adapter for a {@link dev.abunai.confidentiality.analysis.model.uncertainty.ExternalUncertaintySourceInUsage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExternalUncertaintySourceInUsageAdapter() {
		if (externalUncertaintySourceInUsageItemProvider == null) {
			externalUncertaintySourceInUsageItemProvider = new ExternalUncertaintySourceInUsageItemProvider(this);
		}

		return externalUncertaintySourceInUsageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dev.abunai.confidentiality.analysis.model.uncertainty.ExternalUncertaintyInResourceScenario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExternalUncertaintyInResourceScenarioItemProvider externalUncertaintyInResourceScenarioItemProvider;

	/**
	 * This creates an adapter for a {@link dev.abunai.confidentiality.analysis.model.uncertainty.ExternalUncertaintyInResourceScenario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExternalUncertaintyInResourceScenarioAdapter() {
		if (externalUncertaintyInResourceScenarioItemProvider == null) {
			externalUncertaintyInResourceScenarioItemProvider = new ExternalUncertaintyInResourceScenarioItemProvider(this);
		}

		return externalUncertaintyInResourceScenarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dev.abunai.confidentiality.analysis.model.uncertainty.ExternalUncertaintyInUsageScenario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExternalUncertaintyInUsageScenarioItemProvider externalUncertaintyInUsageScenarioItemProvider;

	/**
	 * This creates an adapter for a {@link dev.abunai.confidentiality.analysis.model.uncertainty.ExternalUncertaintyInUsageScenario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExternalUncertaintyInUsageScenarioAdapter() {
		if (externalUncertaintyInUsageScenarioItemProvider == null) {
			externalUncertaintyInUsageScenarioItemProvider = new ExternalUncertaintyInUsageScenarioItemProvider(this);
		}

		return externalUncertaintyInUsageScenarioItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (uncertaintySourceCollectionItemProvider != null) uncertaintySourceCollectionItemProvider.dispose();
		if (behaviorUncertaintySourceItemProvider != null) behaviorUncertaintySourceItemProvider.dispose();
		if (behaviorUncertaintyScenarioItemProvider != null) behaviorUncertaintyScenarioItemProvider.dispose();
		if (externalUncertaintySourceInResourceItemProvider != null) externalUncertaintySourceInResourceItemProvider.dispose();
		if (externalUncertaintySourceInUsageItemProvider != null) externalUncertaintySourceInUsageItemProvider.dispose();
		if (externalUncertaintyInResourceScenarioItemProvider != null) externalUncertaintyInResourceScenarioItemProvider.dispose();
		if (externalUncertaintyInUsageScenarioItemProvider != null) externalUncertaintyInUsageScenarioItemProvider.dispose();
	}

}
