<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uncertainty" nsURI="http://abunai.dev/uncertainty" nsPrefix="uncertainty">
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintySourceCollection" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
        eType="#//UncertaintySource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintySource" abstract="true" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintyScenario" abstract="true"
      eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="-1.0"/>
  </eClassifiers>
  <eSubpackages name="pcm" nsURI="http://abunai.dev/uncertainty/pcm" nsPrefix="pcm">
    <eClassifiers xsi:type="ecore:EClass" name="PCMUncertaintySource" abstract="true"
        eSuperTypes="#//UncertaintySource"/>
    <eClassifiers xsi:type="ecore:EClass" name="PCMExternalUncertaintySource" abstract="true"
        eSuperTypes="#//pcm/PCMUncertaintySource"/>
    <eClassifiers xsi:type="ecore:EClass" name="PCMExternalUncertaintySourceInResource"
        eSuperTypes="#//pcm/PCMExternalUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.nodecharacteristics/model/nodeCharacteristics.ecore#//ResourceAssignee"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/PCMExternalUncertaintyScenarioInResource" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMExternalUncertaintySourceInUsage"
        eSuperTypes="#//pcm/PCMExternalUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.nodecharacteristics/model/nodeCharacteristics.ecore#//UsageAssignee"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/PCMExternalUncertaintyScenarioInUsage" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMExternalUncertaintyScenarioInResource"
        eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.nodecharacteristics/model/nodeCharacteristics.ecore#//ResourceAssignee"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMExternalUncertaintyScenarioInUsage"
        eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.nodecharacteristics/model/nodeCharacteristics.ecore#//UsageAssignee"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMBehaviorUncertaintySource" eSuperTypes="#//pcm/PCMUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/SetVariableAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/PCMBehaviorUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMBehaviorUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/SetVariableAction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMInterfaceUncertaintySource" eSuperTypes="#//pcm/PCMUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/PCMInterfaceUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMInterfaceUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMConnectorUncertaintySource" abstract="true"
        eSuperTypes="#//pcm/PCMUncertaintySource"/>
    <eClassifiers xsi:type="ecore:EClass" name="PCMConnectorUncertaintySourceInExternalCall"
        eSuperTypes="#//pcm/PCMConnectorUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/PCMConnectorUncertaintyScenarioInExternalCall" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMConnectorUncertaintySourceInEntryLevelSystemCall"
        eSuperTypes="#//pcm/PCMConnectorUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//usagemodel/EntryLevelSystemCall"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/PCMConnectorUncertaintyScenarioInEntryLevelSystemCall" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMConnectorUncertaintyScenarioInExternalCall"
        eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMConnectorUncertaintyScenarioInEntryLevelSystemCall"
        eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//usagemodel/EntryLevelSystemCall"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMComponentUncertaintySource" eSuperTypes="#//pcm/PCMUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/PCMComponentUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMComponentUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="dfd" nsURI="http://abunai.dev/uncertainty/dfd" nsPrefix="dfd">
    <eClassifiers xsi:type="ecore:EClass" name="DFDUncertaintySource" abstract="true"
        eSuperTypes="#//UncertaintySource"/>
    <eClassifiers xsi:type="ecore:EClass" name="DFDExternalUncertaintySource" eSuperTypes="#//dfd/DFDUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetProperties" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Label"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//dfd/DFDExternalUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDExternalUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetProperties" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Label"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDBehaviorUncertaintySource" eSuperTypes="#//dfd/DFDUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Behaviour"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetAssignments" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//AbstractAssignment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//dfd/DFDBehaviorUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDBehaviorUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetAssignments" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//AbstractAssignment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDInterfaceUncertaintySource" eSuperTypes="#//dfd/DFDUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetInPin" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Pin"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetFlow" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Flow"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//dfd/DFDInterfaceUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDInterfaceUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetInPin" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Pin"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetFlow" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Flow"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDConnectorUncertaintySource" eSuperTypes="#//dfd/DFDUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetAssignments" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//AbstractAssignment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetFlow" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Flow"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//dfd/DFDConnectorUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDConnectorUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetAssignments" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//AbstractAssignment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetFlow" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Flow"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDComponentUncertaintySource" eSuperTypes="#//dfd/DFDUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//dfd/DFDComponentUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFDComponentUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Node"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
