<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uncertainty" nsURI="http://abunai.dev/uncertainty" nsPrefix="uncertainty">
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintySourceCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
        eType="#//UncertaintySource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintySource" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintyScenario" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eSubpackages name="pcm" nsURI="http://abunai.dev/uncertainty/pcm" nsPrefix="pcm">
    <eClassifiers xsi:type="ecore:EClass" name="ExternalUncertaintySource" abstract="true"
        eSuperTypes="#//UncertaintySource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalUncertaintySourceInResource"
        eSuperTypes="#//pcm/ExternalUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.nodecharacteristics/model/nodeCharacteristics.ecore#//ResourceAssignee"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/ExternalUncertaintyScenarioInResource" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalUncertaintySourceInUsage"
        eSuperTypes="#//pcm/ExternalUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.nodecharacteristics/model/nodeCharacteristics.ecore#//UsageAssignee"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/ExternalUncertaintyScenarioInUsage" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalUncertaintyScenarioInResource"
        eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.nodecharacteristics/model/nodeCharacteristics.ecore#//ResourceAssignee"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalUncertaintyScenarioInUsage"
        eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.nodecharacteristics/model/nodeCharacteristics.ecore#//UsageAssignee"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorUncertaintySource" eSuperTypes="#//UncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/SetVariableAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/BehaviorUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/SetVariableAction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceUncertaintySource" eSuperTypes="#//UncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/InterfaceUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorUncertaintySource" abstract="true"
        eSuperTypes="#//UncertaintySource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorUncertaintySourceInExternalCall"
        eSuperTypes="#//pcm/ConnectorUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/ConnectorUncertaintyScenarioInExternalCall" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorUncertaintySourceInEntryLevelSystemCall"
        eSuperTypes="#//pcm/ConnectorUncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//usagemodel/EntryLevelSystemCall"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/ConnectorUncertaintyScenarioInEntryLevelSystemCall" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorUncertaintyScenarioInExternalCall"
        eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorUncertaintyScenarioInEntryLevelSystemCall"
        eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//usagemodel/EntryLevelSystemCall"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentUncertaintySource" eSuperTypes="#//UncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//pcm/ComponentUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="dfd" nsURI="http://abunai.dev/uncertainty/dfd" nsPrefix="dfd">
    <eClassifiers xsi:type="ecore:EClass" name="ExternalUncertaintySource" eSuperTypes="#//UncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetProperties" lowerBound="1"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Label"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//dfd/ExternalUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetProperties" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Label"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorUncertaintySource" eSuperTypes="#//UncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Behaviour"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetAssignments" ordered="false"
          lowerBound="1" upperBound="-1" eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//AbstractAssignment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//dfd/BehaviorUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetAssignments" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//AbstractAssignment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceUncertaintySource" eSuperTypes="#//UncertaintySource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetPin" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Pin"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetFlow" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Flow"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//dfd/InterfaceUncertaintyScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceUncertaintyScenario" eSuperTypes="#//UncertaintyScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetPin" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Pin"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetFlow" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Flow"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
